"""Assemble the review Markdown and convert to .docx via pandoc.

Output filenames: {YYMMDD}_{project}_litreview_ra.md / .docx
A new datestamp marks a new major revision cycle (new research direction).
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

from haarpi.render import pandoc_convert  # noqa: F401 — re-exported for callers


def build_markdown(cfg, brain_backend: str, narrative: str, biblio: str,
                   corpus, unmatched: list[str], metrics_line: str = "") -> str:
    brain = cfg.brain
    if brain_backend == "claude":
        model_str = brain.claude_model
    else:
        model_str = brain.coordinator_model
    parts = [
        f"# Literature Review: {cfg.topic}",
        "",
        f"*Project:* {cfg.project_name}  ",
        f"*Date:* {date.today().isoformat()}  ",
        f"*Sources:* {len(corpus)}  ",
        f"*Generated by:* rabbitHole — {model_str}  ",
    ]
    if cfg.focus:
        parts.append(f"*Focus:* {cfg.focus}  ")
    if metrics_line:
        # Breadth, depth, and verifiability, in the document itself. A reader should not have
        # to open the run log to learn that the review cites 15 of its 83 curated sources.
        parts.append(f"*Foundation:* {metrics_line}  ")
    parts += ["", "## Narrative Review", "", narrative.strip(), "", biblio.strip(), ""]

    if unmatched:
        parts += [
            "---",
            "",
            "> **Citation check:** the following citekeys could not be matched to "
            "a source in the corpus and should be verified or removed: "
            + "; ".join(f"[@{u}]" for u in unmatched),
            "",
        ]
    return "\n".join(parts)


def write_review(cfg, paths, brain_backend: str, narrative: str, biblio: str,
                 corpus, unmatched: list[str], metrics_line: str = "") -> tuple[Path, Path | None]:
    md = build_markdown(cfg, brain_backend, narrative, biblio, corpus, unmatched, metrics_line)
    today = date.today().strftime("%y%m%d")
    stem = f"{today}_{cfg.project_name}_litreview_ra"
    out_md = paths.output / f"{stem}.md"
    out_md.write_text(md, encoding="utf-8")

    out_docx = paths.output / f"{stem}.docx"
    if pandoc_convert(out_md, out_docx):
        return out_md, out_docx
    return out_md, None
