"""Assemble the review Markdown and convert to .docx via pandoc.

Output filenames carry the brain backend, so A/B runs land side by side:
  output/<project>_litreview_ollama.md   /  ..._claude.md
"""

from __future__ import annotations

import shutil
import subprocess
from datetime import date
from pathlib import Path


def build_markdown(cfg, brain_backend: str, narrative: str, biblio: str,
                   corpus, unmatched: list[str]) -> str:
    brain = cfg.brain
    if brain_backend == "claude":
        model_str = brain.claude_model
    else:
        model_str = brain.coordinator_model
    parts = [
        f"# Literature Review: {cfg.topic}",
        "",
        f"*Project:* {cfg.project_name}  ",
        f"*Date:* {date.today().isoformat()}  ",
        f"*Sources:* {len(corpus)}  ",
        f"*Generated by:* rabbitHole — {model_str}  ",
    ]
    if cfg.focus:
        parts.append(f"*Focus:* {cfg.focus}  ")
    parts += ["", "## Narrative Review", "", narrative.strip(), "", biblio.strip(), ""]

    if unmatched:
        parts += [
            "---",
            "",
            "> **Citation check:** the following in-text citations could not be "
            "matched to a source in the corpus and should be verified or removed: "
            + "; ".join(unmatched),
            "",
        ]
    return "\n".join(parts)


def write_review(cfg, paths, brain_backend: str, narrative: str, biblio: str,
                 corpus, unmatched: list[str]) -> tuple[Path, Path | None]:
    md = build_markdown(cfg, brain_backend, narrative, biblio, corpus, unmatched)
    stem = f"{cfg.project_name}_litreview_{brain_backend}"
    out_md = paths.output / f"{stem}.md"
    out_md.write_text(md, encoding="utf-8")

    out_docx = paths.output / f"{stem}.docx"
    if _pandoc(out_md, out_docx):
        return out_md, out_docx
    return out_md, None


def _pandoc(src: Path, dst: Path) -> bool:
    if not shutil.which("pandoc"):
        print("  [note] pandoc not found — skipping .docx (md written). "
              "Install pandoc to get .docx output.")
        return False
    try:
        subprocess.run(["pandoc", str(src), "-o", str(dst)],
                       check=True, capture_output=True)
        return True
    except subprocess.CalledProcessError as e:
        print(f"  [warn] pandoc failed: {e.stderr.decode()[:200]}")
        return False
