"""Two-tier consumption of the literature review — the harvest, and its inspectable sidecar.

raconteur used to read a blind 12k-char prefix of the review and distil it, unseen, into a
structural analysis. That truncated the review's back half and left no record of what the
paper actually drew on. The two tiers replace it:

  tier 1  the thread INDEX — every ``## `` thread's heading + thesis + citekeys, untruncated,
          so the analysis sees the whole review's shape (see ``context.litreview_index``).
  tier 2  the HARVEST — for each background pillar the analysis proposes, which review threads
          support it, and which threads it left unused. Folded into the analysis JSON so it
          costs no extra model call, then written beside the deliverable as a sidecar.

The sidecar is a verification aid, not a gate: the human still gates the deliverable, but can
now open one file and check that the right threads fed the paper and none were silently dropped
— which is the whole reason the review exists. It is regenerated every run; never hand-edit it.
"""

from __future__ import annotations

import json
from pathlib import Path

from .context import LitThread, litreview_index
from .log import log

_HARVEST_KEY = "litrev_harvest"


def harvest_instruction(threads: list[LitThread]) -> str:
    """The prompt fragment that asks the analysis to also bind pillars → review threads.

    Injected only when the review parsed into threads; empty otherwise, so a flat review keeps
    the original schema untouched. Uses the EXACT thread headings from the index it was shown."""
    if not threads:
        return ""
    return (
        '\nAlso return "litrev_harvest": using the Literature Review Thread Index above, record '
        "which threads the paper draws on. Its value is an object:\n"
        '  {"by_pillar": {"<a background_pillar name>": ["<exact thread heading>", ...], ...},\n'
        '   "unused": ["<exact thread heading the paper does not need>", ...]}\n'
        "Use thread headings EXACTLY as written in the index. Every thread appears once — under "
        "the pillar it supports, or in \"unused\". Do not invent headings.\n"
    )


def _coverage(threads: list[LitThread], parsed: dict) -> tuple[dict[str, list[str]], list[str]]:
    """Normalise the model's harvest into (by_pillar, unused), tolerant of a missing or messy
    field. Every thread lands exactly once: a heading the model bound to no pillar (or forgot)
    falls to ``unused``, and a heading it invented is dropped — the sidecar reflects the real
    review, not the model's spelling of it."""
    real = {t.heading for t in threads}
    harvest = parsed.get(_HARVEST_KEY) or {}
    by_pillar_raw = harvest.get("by_pillar") if isinstance(harvest, dict) else None
    by_pillar: dict[str, list[str]] = {}
    bound: set[str] = set()
    if isinstance(by_pillar_raw, dict):
        for pillar, heads in by_pillar_raw.items():
            kept = [h for h in (heads or []) if h in real and h not in bound]
            if kept:
                by_pillar[str(pillar)] = kept
                bound.update(kept)
    # Anything not bound to a pillar is unused, whatever the model claimed — coverage is total.
    unused = [t.heading for t in threads if t.heading not in bound]
    return by_pillar, unused


def render_sidecar(tag: str, threads: list[LitThread], parsed: dict) -> str:
    """The inspectable sidecar as markdown: tier-1 index, tier-2 harvest, and the analysis."""
    by_pillar, unused = _coverage(threads, parsed)
    out = [
        f"# Lit-review harvest — {tag}",
        "",
        f"_Regenerated by raconteur from {len(threads)} review thread(s). "
        "A verification aid — inspect, do not edit._",
        "",
        "## Tier 1 — thread index (what raconteur saw)",
        "",
        litreview_index(threads) or "_(no threads)_",
        "",
        "## Tier 2 — harvest (what fed the paper)",
        "",
    ]
    if by_pillar:
        for pillar, heads in by_pillar.items():
            out.append(f"### {pillar}")
            out += [f"- {h}" for h in heads]
            out.append("")
    else:
        out += ["_(no pillar bindings recorded)_", ""]
    out.append("### Unused threads")
    out += ([f"- {h}" for h in unused] if unused else ["_(none — every thread was harvested)_"])
    out += ["", "## Analysis (raconteur's extracted structure)", "", "```json",
            json.dumps(parsed, indent=2), "```", ""]
    return "\n".join(out)


def write_sidecar(out_dir: Path, tag: str, threads: list[LitThread], parsed: dict) -> Path | None:
    """Write ``{out_dir}/{tag}.harvest.md``. Best-effort: a sidecar failure never blocks a draft."""
    if not threads:
        return None
    try:
        out_dir.mkdir(parents=True, exist_ok=True)
        path = out_dir / f"{tag}.harvest.md"
        path.write_text(render_sidecar(tag, threads, parsed), encoding="utf-8")
        log(f"[raconteur] wrote litreview harvest sidecar: {path.name}")
        return path
    except OSError as e:                          # a read-only dir, a full disk — note and move on
        log(f"[warn] could not write harvest sidecar ({e})")
        return None
